version: "3.5"
services:
  app:
    image: nextcloud
    environment:
    - NO_PROXY
    - HTTP_PROXY
    - HTTPS_PROXY
    ports:
    - published: ${LISTEN_PORT}
      target: 80
      protocol: tcp
      mode: ingress
    volumes:
    - app:/var/www/html
    depends_on:
    - db
    networks:
    - network
  db:
    image: mariadb
    volumes:
    - db:/var/lib/mysql
    environment:
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
    - network
networks:
  network: {}
volumes:
  app: {}
  db: {}
