version: "3.5"
services:
  app:
    image: nextcloud
    restart: always
    ports:
    - 127.0.0.1:${LISTEN_PORT}:80
    links:
    - db
    volumes:
    - nextcloud:/var/www/html
    depends_on:
    - db
  db:
    image: mariadb
    restart: always
    volumes:
    - db:/var/lib/mysql
    environment:
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
volumes:
  nextcloud:
  db:
